version: '3'
services:
  #PHP Service
  app:
    build:
      args:
        user: maker-checker-user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: maker-checker-app
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker-compose/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - maker-checker-app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: make_checker-server
    restart: unless-stopped
    tty: true
    ports:
      - "6060:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - maker-checker-app-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: make_checker-db
    restart: unless-stopped
    tty: true
    ports:
      - "3330:3306"
    volumes:
      - dbdata:/var/lib/mysql
      # - ./docker-compose/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_DATABASE: maker_checker
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: harmlessprince
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - maker-checker-app-network
#Volumes
volumes:
  dbdata:
    driver: local
#Docker Networks
networks:
  maker-checker-app-network:
    driver: bridge